apiVersion: v1
kind: Namespace
metadata:
  name: urlns
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlmonitor
  namespace: urlns
spec:
  replicas: 1
  selector:
    matchLabels:
      run: urlmonitor
  template:
    metadata:
      labels:
        run: urlmonitor
    spec:
      containers:
      - name: urlmonitor
        image: jalaja/urlimg:1.0
        command: ["/bin/urlmonitor"]
        ports:
            - containerPort: 2112
              name: client
        readinessProbe:
            httpGet:
              path: "/metrics"
              port: 2112
            initialDelaySeconds: 30
            timeoutSeconds: 15
        livenessProbe:
            httpGet:
              path: "/metrics"
              port: 2112
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 100000
            timeoutSeconds: 15

---

apiVersion: v1
kind: Service
metadata:
  name: urlmonitor
  namespace: urlns
  labels:
    run: urlmonitor
spec:
  ports:
  - port: 2112
    name: client
  selector:
    run: urlmonitor

